### ISSUE TITLE
Fails to install on Mac OS X Mavericks / Node.js v0.10.21

### ISSUE THREAD

**Issue by hacksparrow** [jussi-kalliokoski/audiolib.js#85] opened 2013-11-06 16:58 UTC
`npm install audiolib` fails to install the package.

OS: Mac OS X Mavericks
Node.js: v0.10.21
grunt-cli: Installed globally
grunt: Installed locally

Output of the installation attempt:

```
npm http GET https://registry.npmjs.org/audiolib
npm http 304 https://registry.npmjs.org/audiolib
npm http GET https://registry.npmjs.org/cubeb
npm http 304 https://registry.npmjs.org/cubeb

> cubeb@0.2.0 install /Users/yaapa/projects/hacklab/node_modules/audiolib/node_modules/cubeb
> node-gyp rebuild

  CXX(target) Release/obj.target/node-cubeb/src/common.o
  CXX(target) Release/obj.target/node-cubeb/src/constants.o
../src/constants.cpp:4:10: fatal error: 'cubeb/cubeb.h' file not found
#include <cubeb/cubeb.h>
         ^
1 error generated.
make: *** [Release/obj.target/node-cubeb/src/constants.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yaapa/projects/hacklab/node_modules/audiolib/node_modules/cubeb
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by phillyqueso** [comment] 2013-11-06 20:06
+1

**Comment by phillyqueso** [comment] 2013-11-06 21:29
nevermind, I ran xcode-select install, and now it works.

**Comment by hacksparrow** [comment] 2013-11-08 09:22
Didn't work for me.

**Comment by jussi-kalliokoski** [comment] 2013-11-10 19:35
Sounds like a dupe of jussi-kalliokoski/node-cubeb#2

You probably haven't got cubeb properly installed. Make sure that it gets installed in your `$LIBDIR` where your linker can find it and also that the headers are installed somewhere the compiler can include them from, e.g. `/usr/include/`. If the issue persists, please file a bug on [jussi-kalliokoski/node-cubeb](https://github.com/jussi-kalliokoski/node-cubeb), the error is not in audiolib.js. :)

Please refer to [kinetiknz/cubeb](https://github.com/kinetiknz/cubeb) for installation instructions for cubeb.

**Closed as completed by jussi-kalliokoski** 2013-11-10 19:35 UTC
